import{useEffect,useState}from'react';import{useNavigate}from'react-router-dom';import{Maximize,RefreshCw}from'lucide-react';import Logo from'../components/Logo';import MaterialCard from'../components/MaterialCard';import{useAuth}from'../hooks/useAuth';import{useClasses,useMaterials,useSubjects}from'../hooks/useRealtime';export default function Board(){const nav=useNavigate();const{profile,logout}=useAuth();const classes=useClasses();const [chosen, setChosen] = useState(
  () => localStorage.getItem('classboard.boardClass') || ''
);

useEffect(() => {
  if (!chosen && profile?.classId) {
    setChosen(profile.classId);
  }
}, [profile?.classId, chosen]);const[s,setS]=useState('');const subjects=useSubjects(chosen);const mats=useMaterials(chosen,s||undefined);const[seen,setSeen]=useState(0);useEffect(()=>{if(chosen)localStorage.setItem('classboard.boardClass',chosen)},[chosen]);useEffect(()=>{if(mats.length>seen)setSeen(mats.length)},[mats.length,seen]);return <div className="min-h-screen bg-slate-950 p-6 text-white lg:p-10"><header className="flex flex-wrap items-center justify-between gap-5"><Logo large/><div className="flex items-center gap-3"><select aria-label="Assigned class" className="rounded-xl bg-white px-4 py-3 text-lg font-bold text-ink" value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">Select class</option>{classes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="btn bg-white/10" onClick={()=>document.documentElement.requestFullscreen?.()}><Maximize/>Full screen</button><button className="btn bg-white/10" onClick={logout}>Sign out</button></div></header><main className="mx-auto mt-10 max-w-7xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-lg text-emerald-300">LIVE · updates automatically</p><h1 className="mt-1 text-4xl font-black lg:text-6xl">Class Materials</h1></div><div className="flex gap-3 overflow-auto"> <button onClick={()=>setS('')} className={`btn min-h-14 text-lg ${!s?'bg-emerald-500 text-slate-950':'bg-white/10'}`}>All</button>{subjects.map(x=><button key={x.id} onClick={()=>setS(x.id)} className={`btn min-h-14 whitespace-nowrap text-lg ${s===x.id?'bg-emerald-500 text-slate-950':'bg-white/10'}`}>{x.name}</button>)}</div></div><div className="mt-8 space-y-5 text-ink">{!chosen?<div className="rounded-3xl bg-white/10 p-16 text-center text-2xl text-white">Select the classroom once. This device will remember it.</div>:mats.length?mats.map(m=><div key={m.id} onClick={()=>nav('/board/viewer?id='+m.id)} className="cursor-pointer"><MaterialCard m={m} big/></div>):<div className="rounded-3xl bg-white/10 p-16 text-center text-2xl text-white"><RefreshCw className="mx-auto mb-4"/>No materials yet. New uploads will appear here automatically.</div>}</div></main></div>}
